### PR TITLE
Add Z algorithm implementation and test

### PR DESCRIPTION
**Pull request by ekzhang**
Hi there! I really love what you're doing with this repo. I'm also a competitive programmer (IGM on Codeforces https://codeforces.com/profile/ekzhang) and Rust enthusiast, so having a library like this would be super useful.

### Summary

This PR adds the Z algorithm to the library, which is a simple, linear-time alternative to KMP that is useful for some string problems. I ported this from [my own C++ implementation](https://ekzlib.netlify.app/view/z_algorithm.cpp).

Let me know what you think. This is a pretty small change, but I am also interested in porting over some idiomatic [splay tree](https://ekzlib.netlify.app/view/splay_tree.cpp), [treap](https://ekzlib.netlify.app/view/treap.cpp), or [link-cut tree](https://ekzlib.netlify.app/view/lct.cpp) code to Rust, since I'm curious how difficult it would be to implement this with ownership. Also, I would like to use Rust as my main language in a future programming competition. :)

### CODE REVIEW

**Comment by vbarcaru** [comment]
TNX!

În sâm., 24 iul. 2021 la 19:01, Eric Zhang ***@***.***> a
scris:

**Review by EbTech — APPROVED** [review]
Thanks, this is great! I used your PR as an excuse to study the Z-algorithm. I played with your code a bit and derived this version:
```
pub fn z_algorithm(text: &[impl Eq]) -> Vec<usize> {
    let n = text.len();
    let (mut l, mut r) = (1, 1);
    let mut z = Vec::with_capacity(n);
    z.push(n);
    for i in 1..n {
        if r > i + z[i - l] {
            z.push(z[i - l]);
        } else {
            l = i;
            while r < l || (r < n && text[r - i] == text[r]) {
                r += 1;
            }
            z.push(r - i);
        }
    }
    z
}
```
My goal here was to avoid allocating uninitialized zeros, and also to more clearly separate the O(1) case from the case where `r` gets incremented. I'll leave it up to you to decide what the final version should look like. And of course, you're welcome to make future contributions :)

**Comment by ekzhang** [comment]
The reason why I implement it this way is because if you just keep lines 348-350 and remove the two if-blocks before and after it, it is clear that the code is just the naive solution. So the stuff on either side is just an optimization that maintains the invariant that r is incremented on each loop, guaranteeing linear time.

Your code looks pretty clean, and it is probably faster as well(?), but it took a bit longer for me to verify correctness. There’s tricky stuff like the use of l and r to mean two separate things, and how you use r < l in the conditional to dodge the case when the else clause is reached not because z[i-l] actually exceeds the span of the original match, but rather because i exceeds r.

So I don’t think I could remember this code during a contest, but for book code, I think it’s great. I would just advise running it on a problem if you haven’t already, to verify.

**Comment by EbTech** [comment]
`l` and `r` should have the same meaning as they did in your version; is that enough to retain a connection to the naive solution? What do you mean by they meaning "two separate things"? My changes are based on the observation that when `z[i - l]` "wins" in your minimum, the `while` loop will not execute: since we already have knowledge going up to `r`, the only case where testing is necessary is when we want to expand past `r`. And in that case, we might as well work with `r` directly instead of `i + z[i]`. (btw I edited the above code to compare `r < i` instead, so now `l` is only read from in the first branch, and written to in the second.)

Some of the code in this repo took a lot longer to write than would be reasonable during a live contest. On the other hand, ideally the book code would be as easy as possible to use, modify and reason about during a live contest; so if you find that it's not, maybe my approach isn't working. As for testing, should this be centralized somehow? I have one example of an actual problem in the `tests/` directory; would it be cleaner instead to just have a collection of URLs to Codeforces submissions? (though we'd have to remember to keep it in sync with other changes to the repo...)

**Comment by EbTech** [comment]
> how you use r < l in the conditional to dodge the case when the else clause is reached not because z[i-l] actually exceeds the span of the original match, but rather because i exceeds r

If it helps at all, conceptually we can still say that z[i-l] exceeds the span of the original match, in the vacuous sense that the original match is empty in this case.

**Comment by EbTech** [comment]
I merged it with the changes for now. The subject of more rigorous (ideally integrated and automated) testing, based on contest problems, remains open.

Thanks again!

**Pull request merged**
